using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace Advent.Tests
{
    [TestFixture]
    public class Day2InventoryManagementSystemTests
    {
        [Test]
        public void ChecksumFunctionTest1()
        {
            var result = Day2InventoryManagementSystem.ChecksumFunction(_inputs1);
            Assert.AreEqual(result, 12);
            Console.WriteLine($"Checksum: {result}");
        }

        [Test]
        public void ChecksumFunctionTest2()
        {
            var result = Day2InventoryManagementSystem.ChecksumFunction(_inputs2);
            Assert.AreEqual(result, 6370);
            Console.WriteLine($"Checksum: {result}");
        }

        private List<string> _inputs1 = new List<string>
        {
            "abcdef", // 0
            "bababc", // 1 x 2 && 1 x 3
            "abbcde", // 1 x 2
            "abcccd", //          1 x 3
            "aabcdd", // 2 x 2          (but only counts once)
            "abcdee", // 1 x 2
            "ababab"  //          2 x 3 (but only counts once)
                      // 3 * 4 == 12
        };

        private List<string> _partTwo;

        private List<string> _inputs2 = new List<string>
        {
            "rmyxgdlihczskunpfwbgqoeybv",
            "rmyxgdlksczskunpfwbjqkeatv",
            "rmybgdxibczskunpfwbjqoeatv",
            "rmyxgdlirczskuopfwbjqzeatv",
            "rmyxedlrhczskunpfwbyqoeatv",
            "rmyxfdlicczskunpfwbxqoeatv",
            "rmyxgvlihkzskunpfwbsqoeatv",
            "rmyxgdaihczvkunpfwblqoeatv",
            "nmyxgolihczskunpfwbjqieatv",
            "rhyxgdcihczskunifwbjqoeatv",
            "rmfxgdlihczskunpfwbvqgeatv",
            "smyxgdlihczskunsiwbjqoeatv",
            "rmyxgdcihcxskunpfwbrqoeatv",
            "rmyxgdlihczckuiqfwbjqoeatv",
            "rmyxxdwihczskunifwbjqoeatv",
            "rkzxgdlihczskunpfwhjqoeatv",
            "rmypgdlihczskunpfwbrqoeafv",
            "rmyxgplihczvkunpkwbjqoeatv",
            "rqyxgdlihdzskjnpfwbjqoeatv",
            "rmyxgdlihczskqnpswbjqoeaov",
            "mcyxgdlihczmkunpfwbjqoeatv",
            "rmyxgdlohczspunpowbjqoeatv",
            "tmyxgdlihczskunpfwbeqoeltv",
            "rmyxgdlibccskunpfwbjqoegtv",
            "rmyxgdlehczsaunpfwboqoeatv",
            "rmaxgdlihczseunpfwbjqojatv",
            "rmyxgdlijczskynpfwbjboeatv",
            "kmlxgdlilczskunpfwbjqoeatv",
            "rmsxgdlshczskenpfwbjqoeatv",
            "rmbxgdlihcmskgnpfwbjqoeatv",
            "rayxgdlihczskunpfwbjqoeaef",
            "umyxgdlisczskunpfdbjqoeatv",
            "rmyxgdlihczskunsfwbjqieatg",
            "rmbxgdlihczhkunpfwbjqoeamv",
            "rmyxgdlihczskeypfwbjqxeatv",
            "rmyxgkrihczskunptwbjqoeatv",
            "rmyxgdlihczskunpawbjqoexiv",
            "rmyxgdlihcrskqnpfwbjqceatv",
            "rmyxgblihczskjnpfwbjqieatv",
            "rmyggdlidczskunofwbjqoeatv",
            "rmyxgdlghczskunphwbjqomatv",
            "rmqxgdbihczskunpfnbjqoeatv",
            "rvyxgdlihczsgunpfwbjqoeanv",
            "royxgdlnhczskqnpfwbjqoeatv",
            "rmyxgdlihczskugpfwbkqreatv",
            "rmyxfdlihczskunppwejqoeatv",
            "rqyxgdlipczskunpfwbjqoeqtv",
            "rmyxgdlicczskunpnwbjqotatv",
            "rmyxodlihczskxnpfwijqoeatv",
            "rmyxrdyihczskunpftbjqoeatv",
            "rmtxgdyihwzskunpfwbjqoeatv",
            "tmyxcdliiczskunpfwbjqoeatv",
            "rmyxgdlihczskmnpfwbjjoeadv",
            "rmyxgdnihczskunpqwbjqojatv",
            "bmyxgdlihczskcnpfwboqoeatv",
            "rmysgdlihcyskudpfwbjqoeatv",
            "rmyxgdtihczsmuupfwbjqoeatv",
            "rmyxgdlihczssunpffbjqolatv",
            "rmyogdlihczsklnpfwbjqoxatv",
            "rmyxgjlihczskunpfwsjqoyatv",
            "rmyxgalshczskunpfwbuqoeatv",
            "rmyfgdlihczskunqfwbiqoeatv",
            "tmyxgdlihczskunotwbjqoeatv",
            "rmyxpdzihczskuopfwbjqoeatv",
            "rmyfgdlihczskunpfrbgqoeatv",
            "rmyxgdlwhczskhnofwbjqoeatv",
            "rmyxgdlihczsmudpfrbjqoeatv",
            "rmyxgdlihczokanpfwbjqooatv",
            "rmyxrdlihczskunppwjjqoeatv",
            "rmyxgdjihczskwnpowbjqoeatv",
            "mmyxgdlihczikunpfwbjqoeamv",
            "rmyxgflihczshunpwwbjqoeatv",
            "rmytghlihczskunpfwbjqoeatk",
            "rmyxgdlipczmbunpfwbjqoeatv",
            "rmyxgdlihczkkonpfwbjqomatv",
            "rmfxgslihczskunpfwujqoeatv",
            "dmyxgdlihczykunqfwbjqoeatv",
            "rmyxgalihcbskunpgwbjqoeatv",
            "rmyxgdlinczqkunpfwbjqopatv",
            "rmyxgdlihwzslunplwbjqoeatv",
            "rmypgdlihczskdtpfwbjqoeatv",
            "rmsxgdxieczskunpfwbjqoeatv",
            "rmyxgdlihczskwnpfxrjqoeatv",
            "rmyxgdlihzzskunpflbjpoeatv",
            "rslxgdlihczsnunpfwbjqoeatv",
            "rmyxgdlmcczskunpfwbjqoealv",
            "fmkxgdbihczskunpfwbjqoeatv",
            "rmyxgdiigczxkunpfwbjqoeatv",
            "rjyxgnlqhczskunpfwbjqoeatv",
            "ymyxgolihczskunpfmbjqoeatv",
            "hmyxgdlihczskuncfwbjqoejtv",
            "rmyxgqlihczzkunpfwbjqojatv",
            "rmgfgdlihczskunpfwbjgoeatv",
            "rmyxgdlfhczskunpfwbjqweaxv",
            "rmoxtdlihczskunpfwdjqoeatv",
            "ruyxgdlihczskunpfmbjnoeatv",
            "rmnxgflehczskunpfwbjqoeatv",
            "rmyugdlihczskunpfwfjroeatv",
            "rmyxddbihczskunpfwbjqoeutv",
            "rmyxgdlipczskunofbbjqoeatv",
            "gmyxgdlihczskunpfkbjroeatv",
            "rmyxgdllhcpskunpfwbjqqeatv",
            "rmyxgdlihchskunpfwbjqoelcv",
            "mmyxldlihczskuncfwbjqoeatv",
            "ryyxgdlxhczskcnpfwbjqoeatv",
            "rmyxpdlihczskyntfwbjqoeatv",
            "rmhxgdlibczskwnpfwbjqoeatv",
            "rmyxgdlihczskunpfwojbkeatv",
            "qmyxgdlihczskunpfwbjqoyatm",
            "rmyxgdlzhczskunpfwbjqoealr",
            "rmyegdliqczskunpfgbjqoeatv",
            "umyxgdlihczsvunpfwbfqoeatv",
            "rmyxgdoihfzskunpfmbjqoeatv",
            "rmyxgdlihcdskanpmwbjqoeatv",
            "rmyxgdyihczskunpfrbjqoeaov",
            "rcyxgdlihczskuegfwbjqoeatv",
            "rmyxgdlihgwskunpfwbjkoeatv",
            "rpyxgdlihmzskunpfwbjqoeatp",
            "rmyxgdlihhzskunpfwbjaoeapv",
            "rmyxgdsrhczskunpflbjqoeatv",
            "rmrxgdlihczskunpvwbjqoeabv",
            "rmcxgylihczskunpfwbjyoeatv",
            "rmkxgdlyhczsounpfwbjqoeatv",
            "rmyxgdqihczskunmfwbjqoratv",
            "rmyxgdlihczskunpfibjqofath",
            "rmyxgdliqczskunpqwbjqoeaev",
            "rmhxgdlizcjskunpfwbjqoeatv",
            "rmyxgdlfhcwskunpfwbjqoeaqv",
            "rmyxgdlchclskunpfwbdqoeatv",
            "rmyxgdluhczswunpfwbjqoeatt",
            "rmyxgdlzqczskunpfwbjqoeatq",
            "rmdxgdlihszskunpfwbwqoeatv",
            "rmyxgdlihszsvunpfwbjqueatv",
            "rmyxgdlhhczskunpffbjaoeatv",
            "rmrxgdlphczskunpfwbjqreatv",
            "hmyngdxihczskunpfwbjqoeatv",
            "rmyxgdlizczpkunpfwbyqoeatv",
            "rmyxbdlihyzskunlfwbjqoeatv",
            "rmyxgdlipczsqunnfwbjqoeatv",
            "rmyxgdlihcsskunpfxbjqoaatv",
            "rmyxgdljhcznkunpfwbjqfeatv",
            "rmaxgdlihczspunpfwbjqoqatv",
            "rsyxgdlihczskunpfwbjqoehcv",
            "rmyxgjlicczskunpfwbjqoeitv",
            "rwymgvlihczskunpfwbjqoeatv",
            "rmyxgdlipfzskunpfwbjqweatv",
            "rmyxgglihczskunpgwbjqoealv",
            "royxgdlihczskhnpfwbyqoeatv",
            "rmyxgdlihczskvnpfabkqoeatv",
            "rmyxgdlihczskunpfwhjwzeatv",
            "jlyxgdlihczskunpfwbjqzeatv",
            "rmyxgdlihccskunpfwwjqopatv",
            "rmyxgxlihczskuupfwbjqoeahv",
            "rmyxgdcihcbskungfwbjqoeatv",
            "tmyxgdlihczskunpfwbjmoeftv",
            "rkyxgdlioczskmnpfwbjqoeatv",
            "rmyxgdlrhczskulpfwbjaoeatv",
            "rmysgdlihczikunphwbjqoeatv",
            "rmyxgdlihczskuvpfwbjqoeyty",
            "fmyxgdlihczscunpfqbjqoeatv",
            "rfyxgdlihzzrkunpfwbjqoeatv",
            "rmyxgdlikczskunpfwbjqolath",
            "rmyxqdlihjzskunpfwbjqoeamv",
            "rmuxodiihczskunpfwbjqoeatv",
            "rmyygdliucuskunpfwbjqoeatv",
            "rmyxgdliwczskuppawbjqoeatv",
            "rmyxgdlihczskunprwbjqgehtv",
            "imyvgdlihczskunpfwbjqouatv",
            "rgyxgdluhczskunpflbjqoeatv",
            "rmgxgdlihczsdunpfwwjqoeatv",
            "gdyxgdlihczskunpfwbjqoeavv",
            "rmyxgdlihczskunpfwljjoektv",
            "rmexgdlihczskunpfwxjqoeytv",
            "rmyxqdlihcyskuwpfwbjqoeatv",
            "rmyxgdlihczskunpfiyjqcebtv",
            "amyngdlihczskunpfwbjqseatv",
            "rmzxgdlihczykubpfwbjqoeatv",
            "rmyxgdlihczhkuopfwbjsoeatv",
            "rmyxgdlihczskunpfwbaqowztv",
            "rmgxgdlihczslunpfwbjeoeatv",
            "rmytgdlzhczskunrfwbjqoeatv",
            "rmyxgdtihczskunafobjqoeatv",
            "rmyxgdlihczskuflfbbjqoeatv",
            "rmdxgdlihczskunpfwbjqoealj",
            "rbyxgdlihczskuppdwbjqoeatv",
            "rmyxhdiihcwskunpfwbjqoeatv",
            "rmmggdlfhczskunpfwbjqoeatv",
            "rmbxgblihczskuypfwbjqoeatv",
            "rmyxgslihczsjunpjwbjqoeatv",
            "rmyxgdlohczsaunpfwbjboeatv",
            "rmaxgdhihczskunpfwbjooeatv",
            "rmyxidlihczskunpfgbuqoeatv",
            "rmyxgdlihfzckznpfwbjqoeatv",
            "rmaqgdpihczskunpfwbjqoeatv",
            "rmyvgdlirczskunpfobjqoeatv",
            "rmdxgdlihczlkunpxwbjqoeatv",
            "rmyxgdlihczseunpfwbjvdeatv",
            "rmyxgdlihczskuhpfwbjqneath",
            "rmyxrdlihciskunpfwbjqoratv",
            "rmyxgdmihczsqunpftbjqoeatv",
            "rmyxgdlbhczskulpfbbjqoeatv",
            "rmoxgdlihczskunpfwbjqoeesv",
            "rmyxgdlihczskuijfwejqoeatv",
            "rmyxgdlihczskunpfwnkqoxatv",
            "rmyxgdvihmzskuupfwbjqoeatv",
            "rkyxedlihczskunpfcbjqoeatv",
            "rmyxgdjihczskunprwbjqieatv",
            "omyxgqgihczskunpfwbjqoeatv",
            "rmyxydlihczskunpfwkjqoentv",
            "rmbxgdlicczskunpfwbjqteatv",
            "emyxgdlihczskugpfwbjqneatv",
            "dmyxgflihczskunpfwbjqjeatv",
            "umyxgdlihczskunpfwbjloextv",
            "rmyxgdlihczsbunpfwbyqpeatv",
            "rmyxgdrihczsvunpcwbjqoeatv",
            "qmyxgdlihcwsknnpfwbjqoeatv",
            "ymyxgdlihczskunpfsbjqowatv",
            "rmyxgdlbhczskunpnvbjqoeatv",
            "rmyxfdlixczskunpfwbjqoertv",
            "rmyygdlihszrkunpfwbjqoeatv",
            "rmyxgxlihcpskunpfwbjqoeanv",
            "rmyxgdlihczskjnpfwbjqoprtv",
            "rmyxgdlisczfkunpfwbjqoeath",
            "rmyxgdlihczskunpfkbjqoeaji",
            "rmyxgylihczskunpfwbfqoeatl",
            "rmsxgdbihczskunpfwtjqoeatv",
            "smyxgdlihczskunpfwbjqcwatv",
            "rmyxgdlihczskunppjljqoeatv",
            "rmyxgdlihczskulpfdbjooeatv",
            "rmyxgdlihczskunpfibjqcebtv",
            "rmyxadlihczskunpgwbjyoeatv",
            "rmyxgdlihczdkunpvwbjqoeytv",
            "rmyxgdlihcvskunpfwbjxohatv",
            "rmyxgplihczskunpfgbjqoeauv",
            "rmyxgdlihcysrunmfwbjqoeatv",
            "rmyygdlihczskunpfwbjqvewtv",
            "rmyxgdlihczsmunpfwdjnoeatv",
            "rmyxgdbibczskunpfwbjuoeatv",
            "rmyfgdlihczskubpfwbjqoeatp",
            "rmyxgdlihczskuopfzijqoeatv",
            "rmyqgdlihczskunpwwbjqoeanv",
            "imyxgdlihczskunpfwbjqoqytv",
            "rmyxgdlixcoskbnpfwbjqoeatv",
            "rmyxgrlihccskunpfwbjqteatv",
            "rdyxgdlihcpskunpfwbjqoratv",
            "rmyxgdlihkzskunpfwbjmoeatj",
            "rmyxgslihczskcnpfjbjqoeatv",
            "rmyxgdlihczsqunqfwdjqoeatv",
            "rjyxgdlyhczbkunpfwbjqoeatv",
            "rmyxudlihczjkunpfwbjqzeatv"
        };


    }
}
